modLoader="aplp"
loaderVersion="[1,)"
license="MIT"

[[mods]]
    modId="groovylicious"
    version="1.18.2-0.2.0"
    displayName="Groovylicious"
    logoFile="logo.png"
    authors="Paint_Ninja"
    description='''
    Delicious syntax sugar with the power of Groovy!
    '''

[[dependencies.groovylicious]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.60,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.groovylicious]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
